### ISSUE TITLE
Confusing output... Cannot resolve symlink (but no symlinks)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/analyzer_cli#22]
Consider this condition:

```
my_app
  main.dart
  packages/
    foo/
      foo.dart
```

cd into my_app

run this command:

`dartanalyzer --package-root=. main.dart`

Output:

```
~/tmp/tests/one $ dartanalyzer --package-root=. main.dart 
Analyzing [main.dart]...
Canonical failed: ./foo
JavaIOException: IOException FileSystemException: Cannot resolve symbolic links, path = './foo' (OS Error: No such file or directory, errno = 2)
#0      JavaFile.getCanonicalPath (package:analyzer/src/generated/java_io.dart:48)
#1      JavaFile.getCanonicalFile (package:analyzer/src/generated/java_io.dart:43)
#2      PackageUriResolver.getCanonicalFile (package:analyzer/src/generated/source_io.dart:390)
#3      PackageUriResolver.resolveAbsolute (package:analyzer/src/generated/source_io.dart:444)
#4      SourceFactory._internalResolveUri (package:analyzer/src/generated/source.dart:755)
#5      SourceFactory.resolveUri (package:analyzer/src/generated/source.dart:706)
#6      ParseDartTask.resolveDirective (package:analyzer/src/generated/engine.dart:9427)
#7      ParseDartTask.internalPerform.<anonymous closure> (package:analyzer/src/generated/engine.dart:9370)
#8      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:150)
#9      ParseDartTask.internalPerform (package:analyzer/src/generated/engine.dart:9355)
#10     AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6378)
#11     AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6351)
#12     AnalysisContextImpl._cacheDartParseData (package:analyzer/src/generated/engine.dart:2748)
#13     AnalysisContextImpl._getDartParseData (package:analyzer/src/generated/engine.dart:3341)
#14     AnalysisContextImpl.computeKindOf (package:analyzer/src/generated/engine.dart:1663)
#15     AnalyzerImpl._analyzeSync (package:analyzer/src/analyzer_impl.dart:323)
#16     AnalyzerImpl.analyzeSync (package:analyzer/src/analyzer_impl.dart:153)
#17     _runAnalyzer (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:83)
#18     _analyzeAll (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:56)
#19     main (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/pkg/analyzer/bin/analyzer.dart:31)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)


[error] Target of URI does not exist: 'package:foo/foo.dart' (/Users/sethladd/tmp/tests/one/main.dart, line 1, col 8)
[warning] The function 'foo' is not defined (/Users/sethladd/tmp/tests/one/main.dart, line 4, col 3)
1 error and 1 warning found.
```

Expected:

Not an error about a symbolic link. Something more actionable like "package contents not found at package root"

**Comment by pq** [comment]
Duplicated by: https://github.com/dart-lang/sdk/issues/23596
