### ISSUE TITLE
Running dartanalyzer with a bad package-root produces a stack trace.

### ISSUE THREAD

**Issue by pq** [dart-lang/analyzer_cli#55]
For example:
```
[~] $ dartanalyzer --package-root not/here foo.dart
Analyzing [foo.dart]...
Unhandled exception:
FileSystemException: Directory listing failed, path = 'not/here/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._list (dart:io-patch/directory_patch.dart:17)
#1      _Directory.listSync (dart:io/directory_impl.dart:229)
#2      _PackageRootPackageMapBuilder.buildPackageMap (package:analyzer_cli/src/driver.dart:566)
#3      Driver._chooseUriResolutionPolicy (package:analyzer_cli/src/driver.dart:274)
#4      Driver._createAnalysisContext (package:analyzer_cli/src/driver.dart:358)
#5      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:113)
#6      Driver.start (package:analyzer_cli/src/driver.dart:102)
#7      main (file:///Users/pquitslund/src/git/clones/dart/sdk/third_party/pkg/analyzer_cli/bin/analyzer.dart:11)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Instead it should produce a simple message (and error code).

**Comment by pq** [comment]
Fixed w/ 1c7c067084b8946c6d53f9d5d6554d6d8d71ac67.
